# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/blotoutio/solutions.git'
target 'EdgeTagExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for EdgeTagExample
  pod 'EdgeTag'
end
